// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5F-s3JqzkOyfc-7UjfmAp6lKt2z41F0',
    appId: '1:827530244409:web:4053e548af6caa8aee78e8',
    messagingSenderId: '827530244409',
    projectId: 'bikersapp-adc9e',
    authDomain: 'bikersapp-adc9e.firebaseapp.com',
    storageBucket: 'bikersapp-adc9e.firebasestorage.app',
    measurementId: 'G-NKK8XSCNJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBILhVZOQH-s-z0H4FG01D2Ajb-zw9iQTQ',
    appId: '1:827530244409:android:1bcf9079c78f7682ee78e8',
    messagingSenderId: '827530244409',
    projectId: 'bikersapp-adc9e',
    storageBucket: 'bikersapp-adc9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO4kQHdmd-gkBgV-VqRD1jUwq2mDM1QPs',
    appId: '1:827530244409:ios:624be5facd5ffbf3ee78e8',
    messagingSenderId: '827530244409',
    projectId: 'bikersapp-adc9e',
    storageBucket: 'bikersapp-adc9e.firebasestorage.app',
    iosBundleId: 'com.twon.bikerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO4kQHdmd-gkBgV-VqRD1jUwq2mDM1QPs',
    appId: '1:827530244409:ios:624be5facd5ffbf3ee78e8',
    messagingSenderId: '827530244409',
    projectId: 'bikersapp-adc9e',
    storageBucket: 'bikersapp-adc9e.firebasestorage.app',
    iosBundleId: 'com.twon.bikerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP5F-s3JqzkOyfc-7UjfmAp6lKt2z41F0',
    appId: '1:827530244409:web:7f4439bc9e464b62ee78e8',
    messagingSenderId: '827530244409',
    projectId: 'bikersapp-adc9e',
    authDomain: 'bikersapp-adc9e.firebaseapp.com',
    storageBucket: 'bikersapp-adc9e.firebasestorage.app',
    measurementId: 'G-WFCB1B13CE',
  );
}
